routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes, Live New App
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('/resentAllBarcodes', function () {
    $payments = \App\Model\Payment::all();
    $api = (new \App\Http\Controllers\ApiController());
    foreach ($payments as $payment) {
        $api->sendBarcodeForm($payment->id);
    }
});

Auth::routes();
Route::get('/testing', 'ApiController@sendBarcodeForm');

Route::group(['middleware' => 'web'], function() {
    Route::get('/find', 'HomeController@search');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/user/profile/{id}', 'UserController@profile');
    Route::get('/user/ticket/{id}', 'UserController@ticket');
    Route::get('/user/site/{id}', 'UserController@site');
    Route::get('/myticket/{id}', 'SettingController@downloadTicket');

    Route::get('/user/nametag/{id}', 'UserController@nametag');
    Route::any('/user/password', 'UserController@password');
    Route::get('/download/{id}', 'BookingController@downloadPdf');
    Route::get('/search', 'BookingController@search')->name('search');
    Route::get('/search_certificate', 'certificateController@search');
    Route::get('/invoice/feeDelete/{id}', 'InvoiceController@feeDelete');
    Route::post('/invoice/addUserFee/{id}', 'InvoiceController@addUserFee');
    Route::post('/user/getOrganization', 'UserController@getOrganization');
    Route::any('/booking/{id}/card', 'PaymentController@card');
    Route::get('/booking/getAmount', 'BookingController@getNewFeeAmount');
    Route::get('/create_new/{id}', 'BookingController@createNewInvoice');
    Route::post('/setting/getedit', 'SettingController@getEdits');
    Route::post('/certificate/ajax', 'certificateController@showData');
    Route::post('ajaxTable', 'HomeController@dataTable');
    Route::any('/payment/export', 'PaymentController@export');
    Route::any('/users/export/{id}/{event?}', 'UserController@export');
    
     Route::any('/booking/checkEmail', 'BookingController@checkEmail');
      Route::any('/booking/checkPhone', 'BookingController@checkPhone');


    Route::resource('booking', 'BookingController');
    Route::resource('invoice', 'InvoiceController');
    Route::resource('payment', 'PaymentController');
    Route::resource('user', 'UserController');
    Route::resource('inbox', 'InboxController');
    Route::resource('setting', 'SettingController');
    Route::resource('certificate', 'certificateController');


    Route::get('/user/applicants/{id?}/{pg?}', 'UserController@show');
    Route::resource('meeting', 'MeetingController');

        //test
    Route::get('/reports/{id}', 'MeetingController@get_report');
    Route::get('/getmeeting/{id}', 'MeetingController@get');
    Route::get('/participantsreports/{id}', 'MeetingController@get_participants_report');
    Route::get('/testzoom/{id}', 'MeetingController@add_participant');
    Route::get('/report/{id}/{type}', 'HomeController@report');
    Route::get('/getparticipants/{id}', 'MeetingController@getMeetingParticipants');
});

Route::get('/', 'BookingController@landing');
Route::post('/tinymce', function(){
    print_r(request()->all());
});
//Route::get('/create_billing', 'InvoiceController@createBilling');
Route::get('/update_billing', 'InvoiceController@updateBilling');
//Route::get('/update_control', 'InvoiceController@updateControl');

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Model\Invoice;
use App\Model\Invoice_fee;
use App\Model\InvoiceUser;
use App\Model\ZoomMeeting;
use Illuminate\Http\Request;
use \App\Model\User_type;
use \App\Model\Role;
use \App\Model\Fee;
use \App\Model\Event;
use \App\Model\User;
use \App\Model\Setting;
use \App\Model\Profession;
use \App\Model\Sms_template;
use \App\Model\Zoom;
use CodeItNow\BarcodeBundle\Utils\BarcodeGenerator;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use PDF;
use DB;

class SettingController extends Controller {

    public function __construct() {
        if (request('auth') == NULL) {
            $this->middleware('auth');
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $this->data['setting'] = Setting::first();
        return view('setting.index', $this->data);
    }

    public function createBarCode($user_id) {
        $user = User::find($user_id);
        $barcode = new BarcodeGenerator();
        $barcode->setText($user->number);
        $barcode->setType(BarcodeGenerator::Code128);
        $barcode->setScale(2);
        $barcode->setThickness(25);
        $barcode->setFontSize(10);
        return $barcode->generate();
    }

    public function newCreateBarCode($user_id, $event_id) {
        $user = User::find($user_id);
        $barcode = new BarcodeGenerator();
        $barcode->setText($user->number);
        $barcode->setType(BarcodeGenerator::Code128);
        $barcode->setScale(2);
        $barcode->setThickness(25);
        $barcode->setFontSize(10);
        return $barcode->generate();
    }

    public function createTicketParam($user_id) {
        $this->data['barcode'] = $this->createBarCode($user_id);
        $this->data['event'] = Event::first();
        $this->data['user'] = User::find($user_id);
        $invoice = \App\Model\Invoice::where('user_id', $user_id)->first();
        if (!empty($invoice)) {
            $this->data['payment'] = $invoice->payment()->first();
        } else {
            $this->data['payment'] = [];
        }
        $this->data['padding_ticket'] = 1;
        $this->data['id'] = $user_id;
        PDF::setOptions(['dpi' => 150, 'defaultFont' => 'sans-serif']);
        return view('email.ticket_attachment', $this->data);
    }

    public function downloadTicket($user_id) {

        $this->data['barcode'] = $this->createBarCode($user_id);
        $userInvoices = InvoiceUser::where('user_id', $user_id)->orderBy('id', 'desc')->limit(1)->get('invoice_id');
        $invoices = Invoice::whereIn('id', $userInvoices)->get();
        $fee = Invoice_fee::where('virtual', 0)->whereIn('invoice_id', $userInvoices)->first();
        if (!empty($fee)) {
            $this->data['event'] = Event::find($fee->event_id);
            $this->data['user'] = User::find($user_id);
            $invoice = Invoice::where(['id' => $fee->invoice_id])->first();
            if (!empty($invoice)) {
                $this->data['payment'] = $invoice->payment()->first();
            } else {
                $this->data['payment'] = [];
            }

            PDF::setOptions(['defaultFont' => 'sans-serif']);
            $pdf = PDF::loadView('email.ticket_attachment', $this->data);
            return $pdf->download('receipt.pdf');
        }
    }

    public function getUserTicket($user_id = null) {
        $this->data['barcode'] = $this->createBarCode($user_id);
        $this->data['event'] = Event::first();
        $this->data['user'] = User::find($user_id);
        $invoice = \App\Model\Invoice::where('user_id', $user_id)->first();
        if (!empty($invoice)) {
            $this->data['payment'] = $invoice->payment()->first();
        } else {
            $this->data['payment'] = [];
        }
        $this->data['padding_ticket'] = 1;
        $this->data['id'] = $user_id;
        return view('email.ticket_attachment', $this->data);
    }

    public function getUserTicketNew($user_id = null) {
        $this->data['barcode'] = $this->createBarCode($user_id);
        $userInvoices = InvoiceUser::where('user_id', $user_id)->orderBy('id', 'desc')->limit(1)->get('invoice_id');
        $invoices = Invoice::whereIn('id', $userInvoices)->get();
        $fee = Invoice_fee::whereIn('invoice_id', $userInvoices)->first();
        if (!empty($fee)) {
            $this->data['event'] = Event::find($fee->event_id);
            $this->data['user'] = User::find($user_id);
            $invoice = Invoice::where(['id' => $fee->invoice_id])->first();
            if (!empty($invoice)) {
                $this->data['payment'] = $invoice->payment()->first();
            } else {
                $this->data['payment'] = [];
            }
            $this->data['padding_ticket'] = 1;
            $this->data['id'] = $user_id;
            return view('email.ticket_attachment', $this->data);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    public function addPermission() {
        $permission_id = request('id');
        $role_id = request('role_id');
        $data = array(
            'role_id' => $role_id,
            'permission_id' => $permission_id
        );
        $insert_id = DB::table('role_permissions')->insertGetId($data, 'id');
        if ($insert_id > 0) {
            echo 'Success: Added';
        } else {
            echo 'Error: Please Refresh';
        }
    }

    public function removePermission() {
        $permission_id = request('id');
        $role_id = request('role_id');
        $data = array(
            'role_id' => $role_id,
            'permission_id' => $permission_id
        );
        DB::table('role_permissions')->where($data)->delete();
        echo 'Success : Removed';
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        if (isset($request->tag)) {
            return $this->{$request->tag}();
        } else {
            $this->validate($request, [
                "name" => "required",
                "phone" => "required",
                "email" => "required|email",
                "box" => "required",
                "address" => "required"
            ]);
            $setting = Setting::first();
            if(request()->site_mode==3){
                Invoice::where('status',1)->update(['status'=>0]);
            }
            empty($setting) ? Setting::create($request->all()) : $setting->update($request->all());
            return redirect()->back()->with('success', ' Information added successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        if ($id == 'role') {
            $this->data['roles'] = Role::all();
            return view('setting.role', $this->data);
        } else if ($id == 'fee') {
            $this->data['events'] = Event::where('status', 1)->get();
            $this->data['fees'] = Fee::all();
            return view('setting.fee', $this->data);
        } else if ($id == 'event') {
            $this->data['events'] = Event::all();
            return view('setting.event', $this->data);
        } else if ($id == 'profession') {
            $this->data['professions'] = Profession::all();
            return view('setting.profession', $this->data);
        } else if ($id == 'permission') {
            $this->data['roles'] = Role::all();
            $this->data['role_id'] = request('id');
            $this->data['groups'] = \App\Model\Permission_group::all();
            return view('setting.permission', $this->data);
        } else if ($id == 'report') {
            $this->data['reports'] = DB::select('select created_at::date, count(*) from nametag_printlogs group by created_at::date');
            return view('setting.reports', $this->data);
        } else if ($id == 'zoom') {
            $this->data['events'] = Event::where('status', 1)->get();
            $this->data['zoomlinks'] = ZoomMeeting::all();
            return view('setting.zoom', $this->data);
        } else {
            $this->data['users'] = User_type::all();
            return view('setting.usertype', $this->data);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        if (request('user') == 'fee') {
            $validator = Validator::make(request()->all(), [
                        'event_id' => [
                            'required',
                            Rule::unique('fees')->ignore($id, 'id')
                        ],
            ]);
            if ($validator->fails()) {
                $errors = $validator->errors();
                return redirect()->back()->with('error', $errors->first());
            }
            Fee::find($id)->update(request()->all());
        } else if (request('user') == 'event') {
            //return request()->all();
            $event = Event::find($id);
             
            if ($event->virtual == "on") {
                if (!empty(request()->virtual)) {
                    $values = array_merge(request()->all(), ['virtual' => 'on']);
                    Event::find($id)->update($values);

                    $zoom = ZoomMeeting::where('event_id', $id);
                    if ($zoom->count() == 0) {
                        $data['topic'] = $event->name;
                        $data['start_time'] = $event->date;
                        $data['duration'] = 100000;
                        $data['agenda'] = $event->theme;
                        $data['host_video'] = 1;

resources/views/setting/event.blade.php
@extends('layouts.app')

@section('content')
<!-- page start-->

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                Events
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                    <a href="javascript:;" class="fa fa-cog"></a>
                    <a href="javascript:;" class="fa fa-times"></a>
                </span>
            </header>
            <?php if (can_access('add_settings')) { ?>
            <p><br/>&nbsp;&nbsp;&nbsp;<a class="btn btn-success" data-toggle="modal" href="#myModal" onmousedown="reset_form()">
                    Add  New Event
                </a></p>
                   <?php }?>
            <div class="panel-body">
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th class="numeric">Status</th>
                                <th>Location</th>
                                <th>Theme</th>
                                <th>Description</th>  
                                <th>Event Date</th> 
                                <th>Maximum Attendee</th> 
                                <th class="numeric">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            ?>
                            @foreach($events as $event)
                            <tr>
                                <td>{{$i}}</td>
                                <td>{{$event->name}}</td>
                                <td><?= $event->status == 1 ? '<b class="badge bg-success">Active</b>' : '<b class="badge badge-default">In Active</b>' ?></td>
                                <td>{{$event->location}}</td>
                                <td>{{$event->theme}}</td>
                                <td>{{$event->description}}</td>
                                <td class="numeric">{{$event->date}}</td>
                                <td>{{$event->max_attendee}}</td>
                                <td class="numeric">
                                     <?=can_access('delete_settings')? btn_delete('user/' . $event->id, 'event'):'' ?>
                                        <?php if (can_access('edit_settings')) { ?>
                                    <a data-toggle="modal" href="#myModal" onmousedown="open_edit_model('<?= $event->id ?>', '<?= url('setting/' . $event->id . '/edit') ?>')" class="btn btn-xs btn-info">Edit</a>  
                                        <?php } ?>
                                </td>
                            </tr>
                            <?php $i++; ?>
                            @endforeach
                        </tbody>
                    </table>
                </section>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog">
                        <form class="cmxform form-horizontal " id="commentForm" method="post" action="<?= url('user') ?>">

                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="title_page">Add New Event</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="panel-body">
                                        <div class=" form">
                                            <div class="form-group ">
                                                <label for="cname" class="control-label col-lg-3">Name (required)</label>
                                                <div class="col-lg-6">
                                                    <input class=" form-control" id="name" name="name" minlength="2" type="text" required="">
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="amount" class="control-label col-lg-3">Location</label>
                                                <div class="col-lg-6">
                                                    <input class=" form-control" id="location" name="location" minlength="2" type="text" required="">
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="cname" class="control-label col-lg-3">Theme (required)</label>
                                                <div class="col-lg-6">
                                                    <textarea id="theme" class="form-control" name="theme" minlength="2" type="text" required=""></textarea>
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="cname" class="control-label col-lg-3">Description (required)</label>
                                                <div class="col-lg-6">
                                                    <textarea id="description" class="form-control" name="description" minlength="2" type="text" required=""></textarea>
                                                </div>
                                            </div>
                                                 <div class="form-group ">
                                                <label for="date" class="control-label col-lg-3">Event Date</label>
                                                <div class="col-lg-6">
                                                    <input class=" form-control" id="date" name="date" minlength="2" type="date" required="">
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="cname" class="control-label col-lg-3">Max number of Attendee(required)</label>
                                                <div class="col-lg-6">
                                                    <input class=" form-control" id="max_attendee" name="max_attendee" type="number" required="">
                                                </div>
                                            </div>

                                            <div class="form-group ">
                                                <label for="cname" class="control-label col-lg-3">Status(required)</label>
                                                <div class="col-lg-6">
                                                    <select class="form-control" name="status" id="status">
                                                        <option  value="1">Active</option>
                                                        <option value="0">Not Active</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="date" class="control-label col-lg-3">Include Virtual Participation?</label>
                                                <div class="col-lg-3">
                                                    <input class="form-control" id="checkbox" name="virtual" minlength="2" type="checkbox">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <?= csrf_field() ?>
                                    <input type="hidden" name="user" value="event"/>
                                    <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                                    <button class="btn btn-success" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
    </div>
</section>
</div>
</div>
<!-- page end-->
<script type="text/javascript">
    open_edit_model = function (a, b) {
        $.ajax({
            type: 'POST',
            url: "<?= url('setting/getedit') ?>",
            data: {
                "id": a,
                "table": "event"
            },
            dataType: "json",
            success: function (data) {
                $('#title_page').html('Edit Event');
                $('#commentForm').attr('action', b);
                $("#commentForm").attr("method", "get");
                $.each(data, function (i, item) {
                    console.log(i);
                    $('#' + i).val(item);
                    if (i == "virtual") {
                        console.log("This is virtul IDL "+item);
                        if (item == "on") {
                            $("#checkbox").prop('checked', true);
                        } else {
                            $("#checkbox").prop('checked', false);
                        }
                    }
                });
            }
        });
    }
    reset_form = function () {
        $('#title_page').html('Add New Event');
        $('#commentForm').attr('action', '<?= url('user') ?>');
        $("#commentForm").attr("method", "post");
        $("input:not(:hidden)").val('');
        $('.delete').html('Delete');
    }
</script>
@endsection

resources/views/setting/reports.blade.php
@extends('layouts.app')
@section('content')
<!-- page start-->

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                Name Tags Printing Reports
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                    <a href="javascript:;" class="fa fa-cog"></a>
                  
                </span>
            </header>

            <div class="panel-body">
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th class="numeric">Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            ?>
                            @foreach($reports as $report)
                            <tr>
                                <td>{{$i}}</td>
                                <td>{{$report->created_at}}</td>
                                <td class="numeric">{{$report->count}}</td>

                            </tr>
                            <?php $i++; ?>
                            @endforeach
                        </tbody>
                    </table>
                </section>

            </div>
    </div>
</section>
</div>
</div>
<!-- page end-->
@endsection

resources/views/setting/zoom.blade.php
@extends('layouts.app')

@section('content')

<!-- page start-->

<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                Zoom Links
                <span class="tools pull-right">
                    <a href="javascript:;" class="fa fa-chevron-down"></a>
                    <a href="javascript:;" class="fa fa-cog"></a>
                    <a href="javascript:;" class="fa fa-times"></a>
                </span>
            </header>
            <div class="panel-body">
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed dataTable">
                        <thead>
                        <tr>
                            <th>Meeting ID</th>
                            <th>Topic</th>
                            <th>Meeting Link</th>
                            <th>Actions</th>

                        </tr>
                        </thead>
                        <tbody>
                            @foreach($zoomlinks as $zoom)
                            <tr>
                                <td>{{$zoom->meeting_id}}</td>
                                <td>{{$zoom->topic}}</td>

                                <td>
                                    <a href="{{ $zoom->meeting_url }}"> {{ $zoom->meeting_url }}</a>
                                </td>
                                <td>
                                    <a href="{{ route('meeting.show',$zoom->meeting_id) }}" class="btn btn-xs btn-info">MORE DETAILS</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </section>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog modal-lg">
                        <form class="cmxform form-horizontal " id="commentForm" method="post" action="<?= url('user') ?>">

                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="title_page">Meeting Participants</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="panel-body">
                                        <table class="table table-bordered">
                                            <th width="40%">USERNAME</th>
                                            <th width="50%">EMAIL</th>
                                            <th width="10%">STATUS</th>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </section>
    </div>
</div>
<!-- page end-->
<script type="text/javascript">
    open_edit_model = function (a, b) {
        $.ajax({
            type: 'POST',
            url: "<?= url('setting/getedit') ?>",
            data: {
                "id": a,
                "table": "user_type"
            },
            dataType: "json",
            success: function (data) {
                $('#title_page').html('Edit user type');
                $('#commentForm').attr('action', b);
                $("#commentForm").attr("method", "get");
                $.each(data, function (i, item) {
                    console.log(i);
                    $('#' + i).val(item);
                });
            }
        });
    }
    reset_form = function () {
        $('#title_page').html('Add New User Type');
        $('#commentForm').attr('action', '<?= url('user') ?>');
        $("#commentForm").attr("method", "post");
        $("input:not(:hidden)").val('');
        $('.delete').html('Delete');
    }
</script>
@endsection